apiVersion: nebius.ai/v1
kind: JaxJob
metadata:
  name: jax-job-1
  labels:
    app: jax
  annotations:
    jax-job-label: jax
spec:
  replicas: 50
  template:
    metadata:
      labels:
        app: jax
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['bin/sh', '-c', 'sleep 1000']
        ports:
        - containerPort: 80