apiVersion: nebius.ai/v1
kind: JaxJob
metadata:
  name: jax-job
  labels:
    app: jax
  annotations:
    jax-job-label: jax
spec:
  parallelism: 7
  template:
    metadata:
      labels:
        app: jax
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['bin/sh', '-c', 'number=$((RANDOM % 5 + 1)); echo "Random number: $number"; [ $number -eq 1 ] && { echo "Exiting with error"; sleep 120 ; exit 1; } || { echo "Sleeping for 3600 seconds"; sleep 3600; }']
        # resources:
        #   limits:
        #     nvidia.com/gpu: 1 
      #   volumeMounts:
      #   - name: nfs-volume
      #     mountPath: /usr/share/nfs
      # volumes:
      # - name: nfs-volume
      #   nfs:
      #     server: nfs-service.nfs.svc.cluster.local
      #     path: /
