apiVersion: batch/v1
kind: Job
metadata:
  name: job-backoff-limit-per-index-example
  annotations:
    jax-job-label: jax
spec:
  completions: 10
  parallelism: 3
  completionMode: Indexed  # required for the feature
  template:
    spec:
      restartPolicy: Never # required for the feature
      containers:
      containers:
        - name: busybox
          image: busybox
          command: ['bin/sh', '-c', 'sleep 2001;']