apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  ports:
    - name: nfs
      port: 2049
  selector:
    role: nfs-server
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-deployment
spec:
  selector:
    matchLabels:
      role: nfs-server
  replicas: 1
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: k8s.gcr.io/volume-nfs
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: /exports
          volumeMounts:
            - name: nfs-volume
              mountPath: /exports
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
