apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jaxjobs.nebius.ai
spec:
  group: nebius.ai
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                template:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                        annotations:
                          type: object
                          additionalProperties:
                            type: string
                    spec:
                      type: object
                      properties:
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              image:
                                type: string
                              command:
                                type: array
                                items:
                                  type: string
                              ports:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    containerPort:
                                      type: integer
  scope: Namespaced
  names:
    plural: jaxjobs
    singular: jaxjob
    kind: JaxJob
    shortNames:
      - jj
